version: "3.8"
services:
  meilisearch:
    image: getmeili/meilisearch:v1.8
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-development_master_key_for_local}
      - MEILI_DB_PATH=/meili_data
    ports: 
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s