[build]
builder = "nixpacks"

[build.nixpacksConfig]
buildCommand = "npm run build"

[deploy]
startCommand = "npm run db:push:prod && npm run db:indexes:prod && npm start"
restartPolicyType = "always"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
buildCommand = "npm run build"
startCommand = "npm run db:push:prod && npm run db:indexes:prod && npm start"